# 2. Установить tuned и добавить в автозагрузку
- name: Install tuned package
    apt:
      name: tuned
      state: present
      update_cache: yes

- name: Start and enable tuned service
    systemd:
      name: tuned
      state: started
      enabled: yes