apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Переопределение replicas для продакшена
replicas:
  - name: nginx-deployment
    count: 5

# Добавление суффикса к именам
nameSuffix: -prod

# Добавление namespace
namespace: prod

# Добавление общих labels
commonLabels:
  environment: production
  version: "1.0-prod"

# Патчи для изменений
patchesStrategicMerge:
  - patch-resourses.yml