Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 2
    libvirt.cpu_model = "host"
    libvirt.cpu_mode = "host-passthrough"
  end

  config.vm.define "my1" do |my1|
    my1.vm.hostname = "my1"
    my1.vm.network "private_network", ip: "192.168.24.178"
  end
end