---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    env: dev
    purpose: testing

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    env: prod
    purpose: production
