Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048  # Увеличиваем с 512 до 2048 MB
    libvirt.cpus = 2
    libvirt.cpu_model = "host"
    libvirt.cpu_mode = "host-passthrough"
  end

  config.vm.define "my1" do |my1|
    my1.vm.hostname = "my1"
    my1.vm.network "private_network", ip: "192.168.24.178"
  end

  config.vm.define "my2" do |my2|
    my2.vm.hostname = "my2"
    my2.vm.network "private_network", ip: "192.168.24.171"
  end
end